sudo: required
services:
  - docker

before_install:
  - docker build -t kenmarut/react-docker-deploy -f Dockerfile.dev

script:
  - docker run kenmarut/react-docker-deploy npm run test -- --coversage