sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t kenmarut/react-docker-deploy

script:
  - docker run -e CI=true kenmarut/react-docker-deploy npm run test -- --coversage